# Generated by Django 4.0 on 2024-04-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='名称')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='评分')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='卡路里')),
                ('protein', models.FloatField(blank=True, null=True, verbose_name='蛋白质')),
                ('fat', models.FloatField(blank=True, null=True, verbose_name='脂肪')),
                ('sodium', models.FloatField(blank=True, null=True, verbose_name='钠含量"')),
                ('categories', models.CharField(blank=True, max_length=200, null=True, verbose_name='配料')),
            ],
            options={
                'verbose_name': '菜肴',
                'verbose_name_plural': '菜肴',
            },
        ),
    ]
