# Generated by Django 4.0 on 2024-04-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uservisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sodium',
            field=models.FloatField(blank=True, null=True, verbose_name='钠含量'),
        ),
    ]
