# Generated by Django 4.0 on 2024-04-06 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_data_sodium'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uservisit',
            options={'verbose_name': '用户推荐记录', 'verbose_name_plural': '用户推荐记录'},
        ),
        migrations.AlterField(
            model_name='uservisit',
            name='visit_time',
            field=models.DateTimeField(verbose_name='时间'),
        ),
    ]
