# Generated by Django 4.0 on 2024-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_uservisit_options_alter_uservisit_visit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='categories',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='菜品配料与描述'),
        ),
    ]
