# Generated by Django 4.0 on 2024-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthindex',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
    ]
